In [1]:
import GraphData as data

In [2]:
df = data.get_perfs()
df.shape

(114, 29)

In [3]:
df = df.loc[df.N_train >= 40000]

In [124]:
df.columns

Index(['N_train', 'T', 'activation', 'batch_size', 'best_epoch', 'biased',
       'date', 'docs_id', 'drop_rate', 'learning_rate', 'max_doc_size',
       'min_loss', 'min_val_mae', 'min_val_mse', 'momentum', 'my_patience',
       'n_units', 'nb_epochs', 'nesterov', 'num_walks', 'optimizer', 'p', 'q',
       'split_id', 'target', 'train_id', 'walk_length'],
      dtype='object')

In [4]:
x = df.groupby("target").min_val_mse.idxmin().values
df.loc[x][["target", "p", "q", "biased", "min_val_mse", "date", "N_train", "T"]]

target         p         q  biased  min_val_mse              date  \
70        0  0.573311  0.706387    True     0.306284  2019-03-25 01:00   
67        1  0.599773  0.707426    True     0.181369  2019-03-25 00:43   
36        2  0.678674  1.404992    True     0.582827  2019-03-24 22:12   
109       3  0.829333  1.041117    True     0.423577  2019-03-25 04:11   

     N_train           T  
70   60000.0  242.101610  
67   60000.0  169.524658  
36   60000.0  167.101468  
109  60000.0  205.627333

df.loc[x][["p", "q", "min_val_mse"]].mean()

In [16]:
import numpy as np

In [37]:
grid_x, grid_y = np.mgrid[0.5:1.5:5j, 0.5:1.5:5j]

In [38]:
grid_x

array([[0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
       [0.75, 0.75, 0.75, 0.75, 0.75],
       [1.  , 1.  , 1.  , 1.  , 1.  ],
       [1.25, 1.25, 1.25, 1.25, 1.25],
       [1.5 , 1.5 , 1.5 , 1.5 , 1.5 ]])

In [26]:
a[["p", "q"]]

p         q
36   0.678674  1.404992
40   0.694360  1.026208
44   0.552345  1.488211
48   1.294249  0.736183
52   0.851506  0.772891
56   0.783117  1.250922
60   1.407391  0.903370
64   1.064781  1.369940
68   0.599773  0.707426
72   0.573311  0.706387
76   0.638390  0.897281
80   1.329811  0.565396
84   1.373460  1.069532
88   0.640560  0.654513
92   0.925146  1.229164
96   1.040533  0.857713
100  1.053479  0.726896
104  1.187477  0.835085
108  0.829333  1.041117

In [55]:
grid_x, grid_y = np.mgrid[a.p.min():a.p.max():100j, a.q.min():a.q.max():100j]
grid_x, grid_y = grid_x.flatten(), grid_y.flatten()
grid_x

array([0.55234506, 0.55234506, 0.55234506, ..., 1.40739091, 1.40739091,
       1.40739091])

In [56]:
heat = griddata(a[["p", "q"]].values, a.min_val_mse, (grid_x, grid_y), method='cubic')
heat

array([nan, nan, nan, ..., nan, nan, nan])

In [16]:
df.columns

Index(['N_train', 'T', 'activation', 'batch_size', 'best_epoch', 'biased',
       'date', 'docs_id', 'drop_rate', 'learning_rate', 'max_doc_size',
       'min_loss', 'min_val_mae', 'min_val_mse', 'momentum', 'my_patience',
       'n_units', 'nb_epochs', 'nesterov', 'num_walks', 'optimizer', 'p', 'q',
       'split_id', 'target', 'train_id', 'walk_length'],
      dtype='object')

In [11]:
a.min_val_mse

36     0.582827
40     0.793856
44     0.613346
48     0.851464
52     0.777759
56     1.003979
60     1.024099
64     1.083752
68     0.689867
72     0.857728
76     1.147995
80     0.632955
84     0.909629
88     0.665541
92     0.903319
96     0.689648
100    1.096655
104    0.721786
108    0.811094
Name: min_val_mse, dtype: float64

In [19]:
import matplotlib.pyplot as plt

In [20]:
%matplotlib notebook

In [23]:
import seaborn as sns; sns.set()

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
sns.hea